# Generated by Django 2.0.5 on 2018-05-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
