# Generated by Django 2.0.5 on 2018-06-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openair', '0002_auto_20180524_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LogContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openair.LogContext'),
        ),
    ]
