# Generated by Django 2.0.5 on 2018-06-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openair', '0003_auto_20180601_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='context',
        ),
        migrations.AlterField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='LogContext',
        ),
    ]
